AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'managed-aws-educate-classroom

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: managed-aws-educate-classroom
    Description: "A centralized control to all student\u2019s AWS Educate Classroom\
      \ Account.  Educators can create and delete cloudformation stack in all student's\
      \ AWS Account in each AWS Educate Classroom.\n"
    Author: Cyrus Wong
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://cyruswong-sam-repo/175792518e4ac015ab6696d16c4f607e
    ReadmeUrl: s3://cyruswong-sam-repo/64c2d61c0c4dfbba52cd9a719feb0988
    Labels:
    - cloudformation
    HomePageUrl: https://github.com/wongcyrus/managed-aws-educate-classroom
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/wongcyrus/managed-aws-educate-classroom
Parameters:
  SNSTopic:
    Type: String
    Default: ''
  BucketName:
    Type: String
    Default: ''
  StudentCommandEmail:
    Type: String
    Default: ''
  StudentEmailDomains:
    Type: String
    Default: ''
  TeacherCommandEmail:
    Type: String
    Default: ''
  TeacherEmailDomains:
    Type: String
    Default: ''
Globals:
  Function:
    Handler: app.lambdaHandler
    Timeout: 180
    Runtime: nodejs12.x
    Layers:
    - Ref: CommonLayer
    Environment:
      Variables:
        StudentAccountTable:
          Ref: StudentAccountTable
        keyPairBucket:
          Ref: keyPairBucket
Conditions:
  HasSnsTopic:
    Fn::Not:
    - Fn::Equals:
      - Ref: SNSTopic
      - ''
Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: managed-aws-educate-classroom-common-layer
      Description: Common code.
      ContentUri: s3://cyruswong-sam-repo/d7661f678e9c6c7cbb5f8a8ceb5bb822
      CompatibleRuntimes:
      - nodejs12.x
  SetupStudentAccountQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - SetupStudentAccountDeadLetterQueue
          - Arn
        maxReceiveCount: 3
  SetupStudentAccountDeadLetterQueue:
    Type: AWS::SQS::Queue
  SetupStudentAccountSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn:
        Ref: SNSTopic
      Endpoint:
        Fn::GetAtt:
        - SetupStudentAccountQueue
        - Arn
      Protocol: sqs
      FilterPolicy:
        receiver:
        - Ref: StudentCommandEmail
        intentName:
        - RegisterStudentAccountIntent
        senderEmailDomain:
          Fn::Split:
          - ','
          - Ref: StudentEmailDomains
  SetupStudentAccountQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: HasSnsTopic
    Properties:
      Queues:
      - Ref: SetupStudentAccountQueue
      PolicyDocument:
        Version: '2008-10-17'
        Id: PublicationPolicy
        Statement:
        - Sid: Allow-SNS-SendMessage
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - sqs:SendMessage
          Resource:
            Fn::GetAtt:
            - SetupStudentAccountQueue
            - Arn
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: SNSTopic
  SetupStudentAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cyruswong-sam-repo/e7687cd381fd17b0d45b4432667f7e50
      Policies:
      - AmazonDynamoDBFullAccess
      - Fn::If:
        - HasSnsTopic
        - S3ReadPolicy:
            BucketName:
              Ref: BucketName
        - Ref: AWS::NoValue
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Resource: arn:aws:iam::*:role/crossaccountteacher
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - SetupStudentAccountQueue
              - Arn
            BatchSize: 1
  CreateStudentStackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cyruswong-sam-repo/2170956637120acbcdb3644552705e12
      Policies:
      - AmazonDynamoDBFullAccess
      - Fn::If:
        - HasSnsTopic
        - S3ReadPolicy:
            BucketName:
              Ref: BucketName
        - Ref: AWS::NoValue
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Resource: arn:aws:iam::*:role/crossaccountteacher
  CreateClassroomQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - CreateClassroomDeadLetterQueue
          - Arn
        maxReceiveCount: 3
  CreateClassroomDeadLetterQueue:
    Type: AWS::SQS::Queue
  CreateClassroomSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn:
        Ref: SNSTopic
      Endpoint:
        Fn::GetAtt:
        - CreateClassroomQueue
        - Arn
      Protocol: sqs
      FilterPolicy:
        receiver:
        - Ref: TeacherCommandEmail
        intentName:
        - CreateClassroomIntent
        senderEmailDomain:
          Fn::Split:
          - ','
          - Ref: TeacherEmailDomains
  CreateClassroomQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: HasSnsTopic
    Properties:
      Queues:
      - Ref: CreateClassroomQueue
      PolicyDocument:
        Version: '2008-10-17'
        Id: PublicationPolicy
        Statement:
        - Sid: Allow-SNS-SendMessage
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - sqs:SendMessage
          Resource:
            Fn::GetAtt:
            - CreateClassroomQueue
            - Arn
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: SNSTopic
  CreateClassroomFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cyruswong-sam-repo/1922ec3abbb091283112307b9d6fdf12
      Policies:
      - AmazonDynamoDBFullAccess
      - Fn::If:
        - HasSnsTopic
        - S3ReadPolicy:
            BucketName:
              Ref: BucketName
        - Ref: AWS::NoValue
      - LambdaInvokePolicy:
          FunctionName:
            Ref: CreateStudentStackFunction
      Environment:
        Variables:
          CreateStudentStackFunctionArn:
            Fn::GetAtt:
            - CreateStudentStackFunction
            - Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - CreateClassroomQueue
              - Arn
            BatchSize: 1
  DeleteStudentStackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cyruswong-sam-repo/dbf3cd6b77f97b644ae4228527feb22c
      Policies:
      - AmazonDynamoDBFullAccess
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Resource: arn:aws:iam::*:role/crossaccountteacher
  DeleteClassroomQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - DeleteClassroomDeadLetterQueue
          - Arn
        maxReceiveCount: 3
  DeleteClassroomDeadLetterQueue:
    Type: AWS::SQS::Queue
  DeleteClassroomSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn:
        Ref: SNSTopic
      Endpoint:
        Fn::GetAtt:
        - DeleteClassroomQueue
        - Arn
      Protocol: sqs
      FilterPolicy:
        receiver:
        - Ref: TeacherCommandEmail
        intentName:
        - DeleteClassroomIntent
        senderEmailDomain:
          Fn::Split:
          - ','
          - Ref: TeacherEmailDomains
  DeleteClassroomQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: HasSnsTopic
    Properties:
      Queues:
      - Ref: DeleteClassroomQueue
      PolicyDocument:
        Version: '2008-10-17'
        Id: PublicationPolicy
        Statement:
        - Sid: Allow-SNS-SendMessage
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - sqs:SendMessage
          Resource:
            Fn::GetAtt:
            - DeleteClassroomQueue
            - Arn
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: SNSTopic
  DeleteClassroomFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cyruswong-sam-repo/73489ac82d3cdee99b6affd8ae859446
      Policies:
      - AmazonDynamoDBFullAccess
      - Fn::If:
        - HasSnsTopic
        - S3ReadPolicy:
            BucketName:
              Ref: BucketName
        - Ref: AWS::NoValue
      - LambdaInvokePolicy:
          FunctionName:
            Ref: DeleteStudentStackFunction
      Environment:
        Variables:
          DeleteStudentStackFunctionArn:
            Fn::GetAtt:
            - DeleteStudentStackFunction
            - Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - DeleteClassroomQueue
              - Arn
            BatchSize: 1
  StudentAccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: classroomNumber
        AttributeType: N
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: classroomNumber
        KeyType: HASH
      - AttributeName: email
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: emailGSI
        KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: classroomNumber
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
  keyPairBucket:
    Type: AWS::S3::Bucket
Outputs:
  SetupStudentAccountFunction:
    Description: SetupStudentAccountFunction
    Value:
      Fn::GetAtt:
      - SetupStudentAccountFunction
      - Arn
  CreateStudentStackFunction:
    Description: CreateStudentStackFunction
    Value:
      Fn::GetAtt:
      - CreateStudentStackFunction
      - Arn
  DeleteStudentStackFunction:
    Description: DeleteStudentStackFunction
    Value:
      Fn::GetAtt:
      - DeleteStudentStackFunction
      - Arn
